# Generated by Django 5.2.15 on 2026-06-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technologie / IT'), ('finance', 'Finance & Banque'), ('healthcare', 'Sante'), ('retail', 'Commerce & Distribution'), ('manufacturing', 'Industrie & Production'), ('consulting', 'Conseil & Services'), ('education', 'Education'), ('real_estate', 'Immobilier'), ('transport', 'Transport & Logistique'), ('other', 'Autre')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='rc_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N RC / SIRET'),
        ),
    ]
