# Generated by Django 6.0.6 on 2026-06-05 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("invoice_date", models.CharField(blank=True, max_length=20)),
                ("invoice_id", models.CharField(blank=True, max_length=100)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(blank=True, default="MAD", max_length=10),
                ),
                (
                    "expense_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SaaS", "SaaS"),
                            ("Travel", "Voyage"),
                            ("Office", "Bureau"),
                            ("Utilities", "Charges"),
                            ("IT Hardware", "Matériel IT"),
                            ("Consulting & Services", "Consulting"),
                            ("Marketing & Communication", "Marketing"),
                            ("Legal & Compliance", "Juridique"),
                            ("Maintenance & Repair", "Maintenance"),
                            ("Other", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("dit_confidence", models.FloatField(blank=True, null=True)),
                ("dit_label", models.CharField(blank=True, max_length=20)),
                ("dit_is_invoice", models.BooleanField(null=True)),
                ("llm_confidence", models.CharField(blank=True, max_length=10)),
                ("is_valid", models.BooleanField(default=False)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("validation_warnings", models.JSONField(blank=True, default=list)),
                ("attempt_count", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "En cours"),
                            ("validated", "Validée"),
                            ("rejected", "Rejetée (DiT)"),
                            ("need_review", "À réviser"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        default="email", help_text="email | upload", max_length=20
                    ),
                ),
                (
                    "excel_file",
                    models.FileField(blank=True, null=True, upload_to="excel_reports/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
            },
        ),
    ]
