# Generated by Django 6.0.6 on 2026-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicerecord",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="MD5 du fichier — évite les doublons",
                max_length=32,
            ),
        ),
    ]
